# Generated by Django 5.1.3 on 2024-11-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_persona_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='character',
            field=models.TextField(blank=True, null=True),
        ),
    ]
