# Generated by Django 5.1.3 on 2024-11-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_persona_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
